//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.24 at 07:52:35 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "thisSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package stepmod.express2xml.descriptions.util.jaxb;
